package chapter_3;

/**
 * pg. 77
 * Created by Rick on 6/30/2015.
 * This program generates two random numbers and asks the user what the sum of the numbers is. The user's answer is
 * evaluated using a boolean expression. The numbers are generated by the remainder of the current time in milliseconds.
 */
import java.util.Scanner;

public class AdditionQuiz {
    public static void main(String[] args){
        int number1 = (int)(System.currentTimeMillis() % 10);
        int number2 = (int)(System.currentTimeMillis() / 7 % 10);

        // create a Scanner
        Scanner input = new Scanner(System.in);

        System.out.print("What is " + number1 + " + " + number2 + "? ");

        int answer = input.nextInt();

        System.out.println(number1 + " + " + number2 + " + " + " = " + answer + " is " +
                (number1 + number2 == answer));
    }
}
